import type { ICategory } from "../Types/Types";


export const catalogConf:ICategory[] = [
        {id: 1, img:"Gitars.png", text: "Гитары", count: 1542 , path:"Gitars", types: [
            {id: 1, text: "Акустические гитары", path: "akusticheskie-gitary"},
            {id: 2, text: "Электрогитары", path: "elektrogitary"},
            {id: 3, text: "Класические гитары", path: "klassicheskie-gitary"},
            {id: 4, text: "Бас-гитары", path: "bas-gitary"},
            {id: 5, text: "Тюнеры и метрономы для гитары", path: "tyunery-i-metronomy"},
            {id: 6, text: "Струны", path: "struny"},
            {id: 7, text: "Аксессуары для гитар", path: "gitarnye-aksessuary-i-komplektuyushhie"},
            {id: 8, text: "Чехлы и кейсы для гитары", path: "chehly-i-kejsy"}
        ]},
        {id: 3, img:"AccusticSustem.png", text: "Звуковое оборудование", count: 902, path: "zvukovoe-oborudovanie", types: [
            {id: 1, text: "Акустические системы", path: "AccusticSustem"},
            {id: 2, text: "Сабвуферы", path: "sabvufery"},
            {id: 3, text: "Усилители звука", path: "usiliteli-moshhnosti"},
            {id: 4, text: "Контроллеры акустических систем", path: "kontrollery-akusticheskih-sistem"},
            {id: 5, text: "Микшерные пульты", path: "mikshernye-pulty"},
            {id: 6, text: "Компрессоры для микрофона", path: "pribory-obrabotki-zvuka"},
            {id: 7, text: "Проигрыватели и рекордеры", path: "proigryvateli-rekordery"},
            {id: 8, text: "Караоке микрофоны", path: "karaoke-mikrofony-i-sistemy"},
            {id: 9, text: "Аксессуары и комплектующие для звукового оборудования", path: "aksessuary-i-komplektuyushhie-dlya-zvukovogo-oborudovaniya"},
        ]},
        {id: 2, img:"Piano.png", text: "Клавишные инструменты", count: 1004, path: "klavishnye-instrumenty", types: [
            {id: 1, text: "Синтезаторы", path: "sintezatory"},
            {id: 2, text: "Цифровые пианино", path: "czifrovye-pianino"},
            {id: 3, text: "Цифровые органы", path: "czifrovye-organy"},
            {id: 4, text: "Акустические клавишные инструменты", path: "akusticheskie-klavishnye-instrumenty"},
            {id: 5, text: "MIDI-клавиатуры", path: "midi-klaviatury"},
            {id: 6, text: "MIDI контроллеры", path: "midi-kontrollery"},
            {id: 7, text: "Аксессуары для клавишных инструментов", path: "originalnye-aksessuary-dlya-klavishnyh-instrumentov"},
        ]},
        {id: 4, img:"Sintezatory.png", text: "Укулеле", count: 2042, path: "ukulele-i-akssesuary", types: [
            {id: 1, text: "Укулеле", path: "ukulele"},
            {id: 2, text: "Чехлы для укулеле", path: "chehly-dlya-ukulele"},
            {id: 3, text: "Струны для укулеле", path: "struny-dlya-ukulele"},
            {id: 4, text: "Ремни для укулеле", path: "remni-dlya-ukulele"},
            {id: 5, text: "Подставки для укулеле", path: "stojki-i-derzhateli-dlya-ukulele"},
            {id: 6, text: "Каподастры для укулеле", path: "kapodastry-dlya-ukulele"},
            {id: 7, text: "Средства по уходу за укулеле", path: "sredstva-po-uhodu-za-ukulele"},
            {id: 8, text: "Акссесуары для укулеле", path: "drugie-akssesuary-i-komplektuyushhie-dlya-ukulele"},
        ]},
        {id: 5, img:"Gitars.png", text: "Гитары", count: 1542 , path:"Gitars", types: [
            {id: 1, text: "Акустические гитары", path: "akusticheskie-gitary"},
            {id: 2, text: "Электрогитары", path: "elektrogitary"},
            {id: 3, text: "Класические гитары", path: "klassicheskie-gitary"},
            {id: 4, text: "Бас-гитары", path: "bas-gitary"},
            {id: 5, text: "Тюнеры и метрономы для гитары", path: "tyunery-i-metronomy"},
            {id: 6, text: "Струны", path: "struny"},
            {id: 7, text: "Аксессуары для гитар", path: "gitarnye-aksessuary-i-komplektuyushhie"},
            {id: 8, text: "Чехлы и кейсы для гитары", path: "chehly-i-kejsy"}
        ]},
        {id: 6, img:"AccusticSustem.png", text: "Звуковое оборудование", count: 902, path: "zvukovoe-oborudovanie", types: [
            {id: 1, text: "Акустические системы", path: "AccusticSustem"},
            {id: 2, text: "Сабвуферы", path: "sabvufery"},
            {id: 3, text: "Усилители звука", path: "usiliteli-moshhnosti"},
            {id: 4, text: "Контроллеры акустических систем", path: "kontrollery-akusticheskih-sistem"},
            {id: 5, text: "Микшерные пульты", path: "mikshernye-pulty"},
            {id: 6, text: "Компрессоры для микрофона", path: "pribory-obrabotki-zvuka"},
            {id: 7, text: "Проигрыватели и рекордеры", path: "proigryvateli-rekordery"},
            {id: 8, text: "Караоке микрофоны", path: "karaoke-mikrofony-i-sistemy"},
            {id: 9, text: "Аксессуары и комплектующие для звукового оборудования", path: "aksessuary-i-komplektuyushhie-dlya-zvukovogo-oborudovaniya"},
        ]},
        {id: 7, img:"Piano.png", text: "Клавишные инструменты", count: 1004, path: "klavishnye-instrumenty", types: [
            {id: 1, text: "Синтезаторы", path: "sintezatory"},
            {id: 2, text: "Цифровые пианино", path: "czifrovye-pianino"},
            {id: 3, text: "Цифровые органы", path: "czifrovye-organy"},
            {id: 4, text: "Акустические клавишные инструменты", path: "akusticheskie-klavishnye-instrumenty"},
            {id: 5, text: "MIDI-клавиатуры", path: "midi-klaviatury"},
            {id: 6, text: "MIDI контроллеры", path: "midi-kontrollery"},
            {id: 7, text: "Аксессуары для клавишных инструментов", path: "originalnye-aksessuary-dlya-klavishnyh-instrumentov"},
        ]},
        {id: 8, img:"Sintezatory.png", text: "Укулеле", count: 2042, path: "ukulele-i-akssesuary", types: [
            {id: 1, text: "Укулеле", path: "ukulele"},
            {id: 2, text: "Чехлы для укулеле", path: "chehly-dlya-ukulele"},
            {id: 3, text: "Струны для укулеле", path: "struny-dlya-ukulele"},
            {id: 4, text: "Ремни для укулеле", path: "remni-dlya-ukulele"},
            {id: 5, text: "Подставки для укулеле", path: "stojki-i-derzhateli-dlya-ukulele"},
            {id: 6, text: "Каподастры для укулеле", path: "kapodastry-dlya-ukulele"},
            {id: 7, text: "Средства по уходу за укулеле", path: "sredstva-po-uhodu-za-ukulele"},
            {id: 8, text: "Акссесуары для укулеле", path: "drugie-akssesuary-i-komplektuyushhie-dlya-ukulele"},
        ]},
];